# Generated by Django 2.2.16 on 2022-04-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220416_1800'),
        ('users', '0003_auto_20220416_1617'),
    ]

    operations = [
    ]
