# Generated by Django 2.2.16 on 2022-04-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220417_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='reviews.Genres'),
        ),
    ]
