# Generated by Django 2.2.16 on 2022-04-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220417_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['-id']},
        ),
    ]
