# Generated by Django 2.2.16 on 2022-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_genretitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(related_name='genre', through='reviews.GenreTitle', to='reviews.Genres'),
        ),
    ]
