# Generated by Django 2.2.16 on 2022-04-18 16:09

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('reviews', '0009_auto_20220417_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
    ]
